In [3]:
import numpy as np 
import matplotlib.pyplot as plt

In [37]:
a = [[11,12,13], [21,22,23], [31,32,33]]
a
A = np.array(a)
A
print(A.ndim)
print(A.shape)
print(A.size)
print(A[2][2])
print(A[2,2])
print(A)
# Truy cập hàng đầu tiên [0]
# Truy cập phần tử từ 0 -> 1

2
(3, 3)
9
33
33
[[11 12 13]
 [21 22 23]
 [31 32 33]]


array([21, 22, 23])

In [40]:
# Truy cập hàng 1,2 và truy cập cột thứ 3
A[0:2,2]

array([13, 23])

In [45]:
X = np.array([[1,0], [0,1]])
Y = np.array([[2,1],[1,2]])
X + Y 
Z = Y * 2
print(Z)

[[4 2]
 [2 4]]


In [50]:
A = np.array([[0,1,1], [1,0,1]])
B = np.array([[1,1],[1,1],[-1,1]])
Z = np.dot(A,B)
print(Z)
Z.T 

[[0 2]
 [0 2]]


array([[0, 0],
       [2, 2]])

In [52]:
# Quiz 
a = [[1,2,3,4], [5,6,7,8],[9,10,11,12]]
A = np.array(a)
B = np.array([[0,1],[1,0],[1,1],[-1,0]])
print(np.dot(A,B))

[[ 1  4]
 [ 5 12]
 [ 9 20]]
