In [57]:
import time 
import sys 
import numpy as np 

import matplotlib.pyplot as plt 
%matplotlib inline 

In [58]:
# Vẽ các hàm
def Plotvec1(u, z, v):
    ax = plt.axes()
    
    ax.arrow(0,0, *u, head_width=0.05, color = 'r', head_length = 0.1)
    plt.text(*(u+0.1), 'u')
    
    ax.arrow(0,0, *z, head_width=0.05, color = 'b', head_length=0.1)
    plt.text(*(z + 0.1), 'z')
    
    ax.arrow(0,0, *v, head_width =0.05, head_length=0.1)
    plt.text(*(v+0.1), 'v')
    plt.xlim(-2,2)
    plt.ylim(-2,2)



def Plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

In [6]:
a = ["0", 1, "two", "3", 4]
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

0
1
two
3
4


In [7]:
a = np.array([0,1,2,3,4])
a
a.dtype
a[1:4] = 5,6,7
a[[0,3,4]]=10
print(a)

[10  5  6 10 10]


In [10]:
type(a)
a.dtype

dtype('int32')

In [22]:
c  = np.array([20,1,2,3,4])
c[0] = 100
print(c)
d = c[1:4]
print(d)
c[1:3] = 100
print(c)

select = [3,4]
c[select] = 100,100
print(c)


[100   1   2   3   4]
[1 2 3]
[100 100 100   3   4]
[100 100 100 100 100]


In [30]:
a.size
a.shape
mean = c.mean()
mean
print(a)
standard_deviation = c.std()
print(standard_deviation)

[10  5  6 10 10]
0.0


In [33]:
u=np.array([0,1])
v=np.array([1,0])
print(u+v)
print(u*v)
# Tích vô hướng của 2 array khác nhau về chiều dài, thì sẽ trở thành nhân 2 array chứ k phải tích vô hướng 2 vector
print(np.dot(u,v))
z = u + 1
print(z)

[1 1]
[0 0]
0
[1 2]


In [36]:
np.pi
x = [np.array([0, np.pi/2, np.pi])]
# Tính sin của mỗi phần tử trong mảng
y = np.sin(x)
print(y)

[[0.0000000e+00 1.0000000e+00 1.2246468e-16]]


In [43]:
#Linspace trả về các số cách đều nhau trong 1 khoảng chỉ định
np.linspace(-2,2, num=9)
x = np.linspace(0, 2*np.pi, num=100)
y = np.sin(x)
plt.plot(x,y)


In [59]:
a = np.array([-1,1])
b = np.array([1,1])
Plotvec2(a,b)